name: record_for_t

packages:
  - record_for_t
  - record_for_t/example
  - record_android_for_t
  - record_darwin
  - record_linux
  - record_platform_interface
  - record_web
  - record_windows

# Don't generate intellij files
ide:
  intellij: false